version: "3.8"

services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    command: ["-scheme", "http", "-port", "4443", "-external-url", "http://fake-gcs:4443"]
    ports:
      - "4443:4443"
    volumes:
      - ./data:/data

  iceberg-rest:
    image: tabulario/iceberg-rest:latest
    environment:
      - CATALOG_WAREHOUSE=gcs://test-bucket/warehouse
    ports:
      - "8181:8181"

  trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      - ./gcs-key.json:/opt/keys/gcs-key.json:ro
