var podNameSpace = "kubeflow";
var podName = "pipeline-4vqqd-3932826485";
var getCreateTimeSinceEpoch = 1721149200000;
var getLastUpdateTimeSinceEpoch = 1721408399000;
var url = "https://grafana.mon.tipnet.xyz/explore";
var datasource = "loki-core-staging-79yu";
var expr = "{namespace=\\\"".concat(podNameSpace, "\\\",pod=\\\"").concat(podName, "\\\"}|=``");
var panesString = "\n  {\n    \"ghd\": {\n      \"datasource\": \"".concat(datasource, "\",\n      \"queries\": [\n        {\n          \"refId\": \"A\",\n          \"expr\": \"").concat(expr, "\",\n          \"queryType\": \"range\",\n          \"datasource\": { \"type\": \"loki\", \"uid\": \"").concat(datasource, "\" },\n          \"editorMode\": \"builder\"\n        }\n      ],\n      \"range\": { \"from\": \"").concat(getCreateTimeSinceEpoch, "\", \"to\": \"").concat(getLastUpdateTimeSinceEpoch, "\" }\n    }\n  }\n");
var panesJson = JSON.parse(panesString);
var panes = JSON.stringify(panesJson);
console.log(panes);
var grafanaUrl = new URL(url);
grafanaUrl.searchParams.append("schemaVersion", "1");
grafanaUrl.searchParams.append("panes", panes);
grafanaUrl.searchParams.append("orgId", "1");
console.log(grafanaUrl);
console.log(grafanaUrl.toString());
