services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v3
    volumes:
      - /media/ibnu/ibn1tb/immich/library:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Jakarta
      DB_HOSTNAME: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: immich
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:v3
    volumes:
      - /media/ibnu/ibn1tb/immich/cache:/cache
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:18-vectorchord1.1.1-pgvector0.8.5
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    restart: unless-stopped
