version: "3.8"

services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs
    ports:
      - "4443:4443"
    command:
      [
        "-scheme", "http",
        "-port", "4443",
        "-backend", "filesystem",
        "-filesystem-root", "/data"
      ]
    volumes:
      - gcs_data:/data

  gravitino:
    image: apache/gravitino:0.9.1
    container_name: gravitino
    depends_on:
      - fake-gcs
    ports:
      - "8090:8090"  # Gravitino main API
      - "9001:9001"  # Iceberg REST API
    environment:
      - JAVA_OPTS=-Xmx1G
    volumes:
      - ./gravitino/conf:/opt/gravitino/conf
      - gravitino_data:/opt/gravitino/data
    command: >
      /bin/sh -c "
        ./bin/gravitino.sh start
      "

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - gravitino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - trino_data:/data/trino

volumes:
  gcs_data:
  gravitino_data:
  trino_data:
