version: "3.8"

services:
  fake-gcs:
    image: fsouza/fake-gcs-server:latest
    container_name: fake-gcs
    command: ["-scheme", "http", "-port", "4443", "-external-url", "http://fake-gcs:4443", "-backend", "memory"]
    ports:
      - "4443:4443"

  polaris:
    image: apache/polaris:latest
    platform: linux/amd64
    container_name: polaris
    depends_on:
      - fake-gcs
    environment:
      POLARIS_STORAGE_TYPE: "GCS"
      POLARIS_GCS_BUCKET: "iceberg-bucket"
      POLARIS_GCS_PROJECT: "test-project"
      STORAGE_EMULATOR_HOST: "http://fake-gcs:4443"
      GOOGLE_APPLICATION_CREDENTIALS: /workspace/fake-gcs-creds.json
    volumes:
      - ./fake-gcs-creds.json:/workspace/fake-gcs-creds.json:ro
    ports:
      - "8181:8181"

  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - polaris
    environment:
      STORAGE_EMULATOR_HOST: "http://fake-gcs:4443"
      GOOGLE_APPLICATION_CREDENTIALS: /workspace/fake-gcs-creds.json
    ports:
      - "8080:8080"
    volumes:
      - ./trino-catalog/polaris.properties:/etc/trino/catalog/polaris.properties:ro
      - ./fake-gcs-creds.json:/workspace/fake-gcs-creds.json:ro
